version: '3.8'

services:
  app:
    image: saifeddine7/projet_nosql:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    environment:
      NODE_ENV: production
      COUCHDB_HOST: couchdb
      COUCHDB_PORT: 5984
      COUCHDB_USER: 
      COUCHDB_PASSWORD: 
    depends_on:
      - couchdb 

  couchdb:
    image: apache/couchdb:3.3.2
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER:  
      COUCHDB_PASSWORD: 
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
